sectors:
  - Agriculture
  - Trade & Commerce
  - Real Estate
  - Manufacturing
  - Transport
  - Energy
  - Tourism & Hotels
  - Personal Loans
  - Construction
  - Mining
  - Microfinance
  - Health & Education
